<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bill</title>
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
  </head>
  <body>
  <div class="container mt-4">
  <div class="row justify-content-md-center">
    <div class="alert alert-info">
        Bill generated by the Foodtastic online shop for {{Auth::user()->username}} at {{date("d-m-Y H:i:s")}}
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-md-10">
    <div class="list-group">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Product</th>
                <th>producer</th>
                <th>Unit price</th>
                <th>Quantity</th>
                <th>Total price</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandTotal = 0;
            @endphp
            @for($i = 0; $i < count($cart); $i += 2)
                <tr>
                    <td>{{$i + 1}}</td>
                    <td><img src="{{$cart[$i]['product']->image_path}}" width=50 height=50/></td>
                    <td>{{$cart[$i]['product']->name}}</td>
                    <td>{{$cart[$i]['product']->producer->name}}</td>
                    <td>{{$cart[$i]['product']->price}} €</td>
                    <td>
                    {{$cart[$i + 1]['quantity']}}
                    </td>
                    <td>{{$cart[$i]['product']->price * $cart[$i + 1]['quantity']}} €</td>
                    @php
                        @$grandTotal += $cart[$i]['product']->price * $cart[$i + 1]['quantity'];
                    @endphp
                </tr>
            @endfor
        </tbody>
        </table>

        <p class="display-4">Grand total : {{$grandTotal}} €</p>
    </div>
    </div>
  </div>
</div>
  </body>
</html>